name: Sync to Hugging Face hub

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI.

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetches all history to ensure we can push to Hugging Face correctly.

      - name: Add remote
        env:
          HF: ${{ secrets.HUGGINGFACE }}
        run: git remote add space https://Hatim-B:$HF@huggingface.co/spaces/Hatim-B/text_summarizer

      - name: Push to hub
        env:
          HF: ${{ secrets.HUGGINGFACE }}
        run: git push --force https://Hatim-B:$HF@huggingface.co/spaces/Hatim-B/text_summarizer ${{ github.ref_name }}  # Push the current branch to Hugging Face
